### ISSUE TITLE
Won't pass App Store Review

### ISSUE THREAD

**Issue by mgcm** [nathangitter/HomeButton#8]
I'm pretty sure that trying to submit an app with this "feature" to the App Store will result in a rejection.

Not sure if this is a "joke" project but still a nice effort :)

**Comment by josejulio** [comment]
All you say here is covered in the Readme :)

> 
> Will this cause my app to be rejected from the App Store?
> 
> It explicity breaks guideline 5.2.1 due to usage of private API's and probably 5.2.5 as well for mimicking > system UI. So honestly it depends on the mood of the reviewer.
> 
> Is this a joke?
>
> Because satire is sometimes lost over the internet—yes, this is a joke. It was created as a fun April Fool's project. However, we think it's actually a decent re-creation of the home button, and is valuable as a UI/UX experiment.



https://github.com/nathangitter/HomeButton#frequently-asked-questions
